site_name: "EKEEL - Empowering Knowledge Extraction to Empower Learners"
repo_url: https://github.com/ekeel-project/docs/
site_url: https://ekeel-project.github.io/docs/

docs_dir: mkdocs
site_dir: docs

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
        
  features:
    - navigation.top  # Keeps navigation bar fixed at the top
    - navigation.tabs  # Use tabs for navigation
    - navigation.instant  # Load pages instantly without reloads
    - content.code.annotate  # Adds code annotations
    - content.code.copy  # Adds copy-to-clipboard button in code blocks
    - content.tooltips  # Enables tooltips for glossary terms
    
  font:
    text: Source Serif Pro
  
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - mkdocs-pdf
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: numpy
            show_source: true
            show_root_heading: false
  - gen-files:
      scripts:
        - mkdocs/docstring_extractor.py
  - literate-nav:
      nav_file: CODE_INDEX.md
  - section-index  
  
          

nav:
  - Homepage: index.md
  - Deploy:
    - Quickstart: platforms/quickstart.md
    - Local:
      - Annotator: platforms/annotator/install.md
      - Augmentator: platforms/augmentator/install.md
    - Remote:
      - Prerequisites: prerequisites/linux-services.md
      - Codebase Update: remote/pull.md
      - Annotator: platforms/annotator/deploy.md
      - Augmentator: platforms/augmentator/deploy.md
      - Transcriber: platforms/annotator/transcriber/deploy.md
  - Codebase: codebase/
  - Documentation: 
      - Mkdocs: prerequisites/mkdocs.md

extra:
  social:
  - icon: fontawesome/brands/twitter
    link: about:void
  - icon: fontawesome/brands/blogger
    link: https://ekeel.dibris.unige.it/